# Generated by Django 3.2.18 on 2023-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palaeography', '0002_initial_data_from_old_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlDocumentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='Name (English)')),
                ('name_fr', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='Name (Français)')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'List: Materials',
            },
        ),
        migrations.CreateModel(
            name='SlDocumentScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='Name (English)')),
                ('name_fr', models.CharField(db_index=True, max_length=1000, unique=True, verbose_name='Name (Français)')),
            ],
            options={
                'verbose_name': 'Script',
                'verbose_name_plural': 'List: Scripts',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='materials',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='documents', to='palaeography.SlDocumentMaterial'),
        ),
        migrations.AddField(
            model_name='document',
            name='scripts',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='documents', to='palaeography.SlDocumentScript'),
        ),
    ]
